packages:
  - desktop

nodeLinker: hoisted
allowBuilds:
  '@bufbuild/buf': true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
