export const DEFAULT_SIDEBAR_WIDTH = 248;
export const MIN_SIDEBAR_WIDTH = 232;
export const MAX_SIDEBAR_WIDTH = 380;
export const SIDEBAR_COLLAPSE_DRAG_THRESHOLD = 204;

export const DEFAULT_CONTEXT_PANE_WIDTH = 560;
export const MIN_CONTEXT_PANE_WIDTH = 360;
export const MAX_CONTEXT_PANE_WIDTH = 760;
export const CONTEXT_PANE_COLLAPSE_DRAG_THRESHOLD =
  MIN_CONTEXT_PANE_WIDTH - 28;
export const CONTEXT_PANE_EXPAND_DRAG_THRESHOLD = 72;
