from typing import Final

AUTHENTICATION_FAILED: Final = "AUTHENTICATION_FAILED"
INTERNAL_ERROR: Final = "INTERNAL_ERROR"
INVALID_REQUEST: Final = "INVALID_REQUEST"
PROTOCOL_MISMATCH: Final = "PROTOCOL_MISMATCH"
