from typing import Final

AUTHENTICATION_FAILED: Final = "AUTHENTICATION_FAILED"
INTERNAL_ERROR: Final = "INTERNAL_ERROR"
INVALID_REQUEST: Final = "INVALID_REQUEST"
MCP_CONNECTION_ERROR: Final = "MCP_CONNECTION_ERROR"
MODEL_PROVIDER_ERROR: Final = "MODEL_PROVIDER_ERROR"
PROTOCOL_MISMATCH: Final = "PROTOCOL_MISMATCH"
