nodeLinker: hoisted
blockExoticSubdeps: false
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: set this to true or false
onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
